---
openapi: "3.0.1"
info:
  title: "tokenizer-p-tokenizer-api"
  description: "Tokenizer API documentation"
  version: "1.0-SNAPSHOT"
servers:
  - url: "https://api.tokenizer.pdv.pagopa.it/{basePath}"
    variables:
      basePath:
        default: "/tokenizer/v1"
paths:
  /tokens/search:
    post:
      operationId: "searchUsingPOST"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PiiResource"
        required: true
      responses:
        200:
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenResource"
        400:
          description: "400 response"
          content: {}
        403:
          description: "403 response"
          content: {}
        404:
          description: "404 response"
          content: {}
        429:
          description: "429 response"
          content: {}
      security:
        - api_key: []
  /tokens/{token}/pii:
    get:
      operationId: "findPiiUsingGET"
      parameters:
        - name: "token"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        200:
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PiiResource"
        400:
          description: "400 response"
          content: {}
        403:
          description: "403 response"
          content: {}
        404:
          description: "404 response"
          content: {}
        429:
          description: "429 response"
          content: {}
      security:
        - api_key: []
  /tokens:
    put:
      operationId: "saveUsingPUT"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PiiResource"
        required: true
      responses:
        200:
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenResource"
        400:
          description: "400 response"
          content: {}
        403:
          description: "403 response"
          content: {}
        404:
          description: "404 response"
          content: {}
        429:
          description: "429 response"
          content: {}
      security:
        - api_key: []
components:
  schemas:
    PiiResource:
      title: "PiiResource"
      required:
        - "pii"
      type: "object"
      properties:
        pii:
          type: "string"
          description: "Personal Identifiable Information"
    TokenResource:
      title: "TokenResource"
      required:
        - "token"
      type: "object"
      properties:
        token:
          type: "string"
          description: "Namespaced token related to the PII"
          format: "uuid"
  securitySchemes:
    api_key:
      type: "apiKey"
      name: "x-api-key"
      in: "header"
