name: Opex Dashboard api_support review

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'apps/io-func-sign-support/openapi.yaml'
      - '.github/workflows/opex_api_support.yaml'
      - '.opex/api_support/**'

env:
  API_NAME: api_support

permissions:
  id-token: write
  contents: read

jobs:
  opex-review:
    runs-on: ubuntu-latest
    environment: opex-prod-ci
    steps:
      - name: Checkout
        id: checkout
        # from https://github.com/actions/checkout/commits/main
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Validate opex dashboard
        uses: ./.github/workflows/opex-review
        with:
          environment: prod
          api_name: ${{ env.API_NAME }}
